INPUT_TAGS = 'input tags'
OUTPUT_TAGS = 'output tags'
TIME_STEPS = 'time steps'
BATCH_SIZE = 'batch size'
TENSOR_BOARD_LOGDIR = './logs'
ALL_TAGS = 'all tags'
EPOCH = 'epoch'
VALIDATION_PART = 'valid part'
