#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Mon Apr  9 03:31:17 2018
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import gettext

import wx

from my_topWindow import MyTopWindow


class MyApp(wx.App):
    def OnInit(self):
        self.frame_1 = MyTopWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_1)
        self.frame_1.Show()
        return True


# end of class MyApp

if __name__ == "__main__":
    gettext.install("app")  # replace with the appropriate catalog name

    app = MyApp(0)
    app.MainLoop()
