# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.0 on Mon Apr  9 06:43:25 2018
#

import wx


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class topWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: topWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.button_1 = wx.Button(self, wx.ID_ANY, _("button_1"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.let_lstm_config_dialog, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: topWindow.__set_properties
        self.SetTitle(_("frame_1"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: topWindow.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(self.button_1, 0, 0, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        # end wxGlade

    def let_lstm_config_dialog(self, event):  # wxGlade: topWindow.<event_handler>
        print("Event handler 'let_lstm_config_dialog' not implemented!")
        event.Skip()

# end of class topWindow
